# Clash 基础配置：由 clash.ini 的 clash_rule_base 引用。
# 订阅转换会在此基础上生成 proxies / proxy-groups / rules。

mixed-port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
ipv6: true
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'

experimental:
  ignore-resolve-fail: true

dns:
  enable: true
  listen: '127.0.0.1:5334'
  default-nameserver: [180.184.1.1, 119.29.29.29, 223.5.5.5]
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  use-system-hosts: true
  nameserver: ['https://223.6.6.6/dns-query', 'https://doh.pub/dns-query']
  nameserver-policy:
    'douban01.45090135.xyz': ['https://anycast.bytecdns.com/913b04c3', 'https://anycast.soufunimgs.com/5428ab28', 'https://anycast.jllyzx.com/8c28d4s7', 'https://anycast.pzwzs.com/3b04c545', 'https://anycast.qccnb.com/a192b791', 'https://anycast.xhspic.com/8c28d4s7', 'https://91c7e35b.qluomcd.com:4443/5428ab28']
    'douban03.45090135.xyz': ['https://anycast.bytecdns.com/913b04c3', 'https://anycast.soufunimgs.com/5428ab28', 'https://anycast.jllyzx.com/8c28d4s7', 'https://anycast.pzwzs.com/3b04c545', 'https://anycast.qccnb.com/a192b791', 'https://anycast.xhspic.com/8c28d4s7', 'https://91c7e35b.qluomcd.com:4443/5428ab28']
    'douban02.45090135.xyz': ['https://anycast.bytecdns.com/913b04c3', 'https://anycast.soufunimgs.com/5428ab28', 'https://anycast.jllyzx.com/8c28d4s7', 'https://anycast.pzwzs.com/3b04c545', 'https://anycast.qccnb.com/a192b791', 'https://anycast.xhspic.com/8c28d4s7', 'https://91c7e35b.qluomcd.com:4443/5428ab28']
