# Shadowrocket分流配置


[General]

bypass-system = true

skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local

tun-excluded-routes = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.168.0.0/16

dns-server = 119.29.29.29,114.114.114.114,223.5.5.5,system

fallback-dns-server = system

ipv6 = false

prefer-ipv6 = false

dns-fallback-system = false

dns-direct-system = false

icmp-auto-reply = true

always-reject-url-rewrite = false

private-ip-answer = false


[Rule]

# 📍 GPS
DOMAIN,gps.ios4001177.workers.dev,PROXY

# 🧲 AI应用
RULE-SET,https://yfamilys.com/rule/ai.list,PROXY

# Ⓜ️ 微软服务
RULE-SET,https://yfamilys.com/rule/Microsoft.list,DIRECT

# 🍎 苹果服务
RULE-SET,https://yfamilys.com/rule/Apple.list,DIRECT
RULE-SET,https://yfamilys.com/rule/AppStore.list,DIRECT
RULE-SET,https://yfamilys.com/rule/AppleProxy.list,PROXY

# 📠 Telegram
RULE-SET,https://yfamilys.com/rule/Telegram.list,PROXY

# 🧣 微博
RULE-SET,https://yfamilys.com/rule/Weibo.list,DIRECT

# 👤 微信
RULE-SET,https://yfamilys.com/rule/WeChat.list,DIRECT

# 🐦 Twitter
RULE-SET,https://yfamilys.com/rule/Twitter.list,PROXY

# 🧟 游戏
RULE-SET,https://yfamilys.com/rule/PlayStation.list,DIRECT
RULE-SET,https://yfamilys.com/rule/Epic.list,DIRECT
RULE-SET,https://yfamilys.com/rule/Sony.list,DIRECT
RULE-SET,https://yfamilys.com/rule/Steam.list,DIRECT
DOMAIN-KEYWORD,ubisoft,DIRECT
RULE-SET,https://yfamilys.com/rule/Nintendo.list,DIRECT
RULE-SET,https://yfamilys.com/rule/WanMeiShiJie.list,DIRECT
DOMAIN-KEYWORD,steam,DIRECT
RULE-SET,https://yfamilys.com/rule/Blizzard.list,DIRECT

# 🎻 Spotify
RULE-SET,https://yfamilys.com/rule/Spotify.list,PROXY

# 🪙 PayPal
RULE-SET,https://yfamilys.com/rule/PayPal.list,PROXY

# 👤 Facebook
RULE-SET,https://yfamilys.com/rule/Facebook.list,PROXY

# 🐦 Reddit
RULE-SET,https://yfamilys.com/rule/Reddit.list,PROXY

# 🐦 Discord
RULE-SET,https://yfamilys.com/rule/Discord.list,PROXY

# 🎬 YouTube
RULE-SET,https://yfamilys.com/rule/YouTube.list,PROXY
RULE-SET,https://yfamilys.com/rule/YouTubeMusic.list,PROXY

# 🎬 Netflix
RULE-SET,https://yfamilys.com/rule/Netflix.list,PROXY

# 🎬 Disney+
RULE-SET,https://yfamilys.com/rule/Disney.list,PROXY

# 🎬 哔哩哔哩
DOMAIN-SUFFIX,api.bilibili.com,DIRECT
RULE-SET,https://yfamilys.com/rule/BiliBili.list,DIRECT

# 🌎 国内媒体
RULE-SET,https://yfamilys.com/rule/ChinaMedia.list,DIRECT

# 🌎 国外媒体
RULE-SET,https://yfamilys.com/rule/ProxyMedia.list,PROXY

# 🎨 Twitch
RULE-SET,https://yfamilys.com/rule/Twitch.list,PROXY

# 🎨 斗鱼
RULE-SET,https://yfamilys.com/rule/Douyu.list,DIRECT

# 🎯 Google
RULE-SET,https://yfamilys.com/rule/Google.list,PROXY

# 🇨🇳 China Max
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/ChinaMax/ChinaMax.list,DIRECT

# 🇨🇳 中国IP直连
RULE-SET,https://yfamilys.com/rule/ASN-CN.list,DIRECT

# 🌎 通用代理
RULE-SET,https://yfamilys.com/rule/Proxy.list,PROXY
DOMAIN-SET,https://yfamilys.com/rule/Proxy.list,PROXY

# ♻️ 漏网之鱼
FINAL,PROXY


[URL Rewrite]

^https?://(www\.)?g\.cn https://www.google.com 302

^https?://(www\.)?google\.cn https://www.google.com 302
